version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bank_adapter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your-password
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bankadapter.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - '5051:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
